#!/bin/sh

case "$1" in
    start)
        echo "Loading aesdchar module"

        modprobe aesdchar || insmod /lib/modules/$(uname -r)/aesdchar.ko

        major=$(awk '$2=="aesdchar" {print $1}' /proc/devices)

        rm -f /dev/aesdchar
        mknod /dev/aesdchar c $major 0
        chmod 666 /dev/aesdchar
        ;;
    stop)
        echo "Unloading aesdchar module"
        rm -f /dev/aesdchar
        rmmod aesdchar
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac